const BASE = '/pms';

export const PMS_API = {
  dashboard: `${BASE}/dashboard`,
  ownerDashboard: `${BASE}/dashboard/owner`,
  reservations: `${BASE}/reservations`,
  reservation: (id: string) => `${BASE}/reservations/${id}`,
  cancelReservation: (id: string) => `${BASE}/reservations/${id}/cancel`,
  duplicateReservation: (id: string) => `${BASE}/reservations/${id}/duplicate`,
  transferReservation: (id: string) => `${BASE}/reservations/${id}/transfer`,
  guests: `${BASE}/guests`,
  guest: (id: string) => `${BASE}/guests/${id}`,
  rooms: `${BASE}/rooms`,
  roomInventory: `${BASE}/rooms/inventory`,
  roomStatus: (id: string) => `${BASE}/rooms/${id}/status`,
  roomBlocks: `${BASE}/rooms/blocks`,
  roomTransfer: `${BASE}/rooms/transfer`,
  checkInStart: (id: string) => `${BASE}/check-in/${id}/start`,
  checkIn: (id: string) => `${BASE}/check-in/${id}`,
  checkInStep: (id: string) => `${BASE}/check-in/${id}/step`,
  checkOut: (id: string) => `${BASE}/check-out/${id}`,
  checkOutComplete: (id: string) => `${BASE}/check-out/${id}/complete`,
  folioCharges: `${BASE}/folio/charges`,
  restaurantCharge: `${BASE}/folio/restaurant-charge`,
  calendar: `${BASE}/calendar`,
  availability: `${BASE}/calendar/availability`,
  search: `${BASE}/search`,
  reports: (type: string) => `${BASE}/reports/${type}`,
  nightAudit: `${BASE}/night-audit`,
  runNightAudit: `${BASE}/night-audit/run`,
  groups: `${BASE}/groups`,
  corporate: `${BASE}/corporate`,
  invoices: `${BASE}/invoices`,
} as const;
