const BASE = '/crm';

export const CRM_ROUTES = {
  home: '/app/crm',
  guests: '/app/crm/guests',
  guestProfile: (id: string) => `/app/crm/guests/${id}`,
  segments: '/app/crm/segments',
  leads: '/app/crm/leads',
  pipeline: '/app/crm/pipeline',
  loyalty: '/app/crm/loyalty',
  points: '/app/crm/points',
  corporate: '/app/crm/corporate',
  travelAgents: '/app/crm/travel-agents',
  campaigns: '/app/crm/campaigns',
  email: '/app/crm/email',
  whatsapp: '/app/crm/whatsapp',
  sms: '/app/crm/sms',
  automation: '/app/crm/automation',
  coupons: '/app/crm/coupons',
  giftCards: '/app/crm/gift-cards',
  referrals: '/app/crm/referrals',
  feedback: '/app/crm/feedback',
  reviews: '/app/crm/reviews',
  upsell: '/app/crm/upsell',
  analytics: '/app/crm/analytics',
  owner: '/app/crm/owner',
  reports: '/app/crm/reports',
  mobile: '/app/crm/mobile',
  ai: '/app/crm/ai',
} as const;

export const CRM_API = {
  dashboard: `${BASE}/dashboard`,
  ownerDashboard: `${BASE}/owner-dashboard`,
  analytics: `${BASE}/analytics`,
  seed: `${BASE}/seed`,
  guests: `${BASE}/guests`,
  guest: (id: string) => `${BASE}/guests/${id}`,
  timeline: (id: string) => `${BASE}/guests/${id}/timeline`,
  segments: `${BASE}/segments`,
  leads: `${BASE}/leads`,
  leadStatus: (id: string) => `${BASE}/leads/${id}/status`,
  pipeline: `${BASE}/pipeline`,
  loyaltyMembers: `${BASE}/loyalty/members`,
  loyaltyTransactions: `${BASE}/loyalty/transactions`,
  loyaltyProgram: `${BASE}/loyalty/program`,
  loyaltyPoints: `${BASE}/loyalty/points`,
  campaigns: `${BASE}/campaigns`,
  automation: `${BASE}/automation`,
  email: `${BASE}/communications/email`,
  whatsapp: `${BASE}/communications/whatsapp`,
  sms: `${BASE}/communications/sms`,
  coupons: `${BASE}/coupons`,
  giftCards: `${BASE}/gift-cards`,
  referrals: `${BASE}/referrals`,
  corporate: `${BASE}/corporate`,
  travelAgents: `${BASE}/travel-agents`,
  feedback: `${BASE}/feedback`,
  reviews: `${BASE}/reviews`,
  report: (type: string) => `${BASE}/reports/${type}`,
} as const;

export const CRM_NAV = [
  { label: 'Dashboard', href: CRM_ROUTES.home },
  { label: 'Guests', href: CRM_ROUTES.guests },
  { label: 'Segments', href: CRM_ROUTES.segments },
  { label: 'Leads', href: CRM_ROUTES.leads },
  { label: 'Pipeline', href: CRM_ROUTES.pipeline },
  { label: 'Loyalty', href: CRM_ROUTES.loyalty },
  { label: 'Points', href: CRM_ROUTES.points },
  { label: 'Corporate', href: CRM_ROUTES.corporate },
  { label: 'Travel Agents', href: CRM_ROUTES.travelAgents },
  { label: 'Campaigns', href: CRM_ROUTES.campaigns },
  { label: 'Email', href: CRM_ROUTES.email },
  { label: 'WhatsApp', href: CRM_ROUTES.whatsapp },
  { label: 'SMS', href: CRM_ROUTES.sms },
  { label: 'Automation', href: CRM_ROUTES.automation },
  { label: 'Coupons', href: CRM_ROUTES.coupons },
  { label: 'Gift Cards', href: CRM_ROUTES.giftCards },
  { label: 'Referrals', href: CRM_ROUTES.referrals },
  { label: 'Feedback', href: CRM_ROUTES.feedback },
  { label: 'Reviews', href: CRM_ROUTES.reviews },
  { label: 'Upsell', href: CRM_ROUTES.upsell },
  { label: 'Analytics', href: CRM_ROUTES.analytics },
  { label: 'Owner', href: CRM_ROUTES.owner },
  { label: 'Reports', href: CRM_ROUTES.reports },
  { label: 'Mobile', href: CRM_ROUTES.mobile },
  { label: 'AI', href: CRM_ROUTES.ai },
] as const;

export function isCrmRoute(pathname: string): boolean {
  return pathname === '/app/crm' || pathname.startsWith('/app/crm/');
}
