/**
 * Fine-grained permission keys for TungaOS RBAC.
 * Format: module:resource:action
 */

export const PERMISSION_ACTIONS = [
  'create',
  'read',
  'update',
  'delete',
  'approve',
  'reject',
  'export',
  'import',
  'print',
] as const;

export const PERMISSION_MODULES = {
  FRONT_DESK: 'frontdesk',
  RESERVATIONS: 'reservations',
  ROOMS: 'rooms',
  HOUSEKEEPING: 'housekeeping',
  RESTAURANT: 'restaurant',
  GXP: 'gxp',
  FINANCE: 'finance',
  INVENTORY: 'inventory',
  PROCUREMENT: 'procurement',
  MAINTENANCE: 'maintenance',
  CRM: 'crm',
  EVENTS: 'events',
  CORP_SALES: 'corp-sales',
  TRAVEL_DESK: 'travel-desk',
  REPORTS: 'reports',
  SETTINGS: 'settings',
  USERS: 'users',
  HOTEL: 'hotel',
  PAYROLL: 'payroll',
  HR: 'hr',
  WEBSITE: 'website',
  AI: 'ai',
} as const;

/** Menu visibility permission keys */
export const MENU_PERMISSIONS = {
  dashboard: 'dashboard:overview:read',
  frontdesk: 'frontdesk:operations:read',
  reservations: 'reservations:booking:read',
  rooms: 'rooms:room:read',
  housekeeping: 'housekeeping:task:read',
  restaurant: 'restaurant:order:read',
  gxp: 'gxp:portal:read',
  finance: 'finance:ledger:read',
  inventory: 'inventory:stock:read',
  procurement: 'procurement:order:read',
  maintenance: 'maintenance:asset:read',
  hr: 'payroll:salary:read',
  crm: 'crm:lead:read',
  events: 'events:booking:read',
  corpSales: 'corp-sales:company:read',
  travelDesk: 'travel-desk:trip:read',
  reports: 'reports:report:read',
  settings: 'settings:config:read',
} as const;

/** Management-level permissions */
export const MANAGEMENT_PERMISSIONS = {
  manageUsers: 'users:user:manage',
  manageHotel: 'hotel:property:manage',
  manageFinance: 'finance:ledger:manage',
  managePayroll: 'payroll:salary:manage',
  manageInventory: 'inventory:stock:manage',
  manageProcurement: 'procurement:order:manage',
  manageMaintenance: 'maintenance:asset:manage',
  manageHr: 'hr:employee:manage',
  manageCrm: 'crm:lead:manage',
  manageEvents: 'events:booking:manage',
  manageCorpSales: 'corp-sales:company:manage',
  manageTravelDesk: 'travel-desk:trip:manage',
  manageReservations: 'reservations:booking:manage',
  manageRooms: 'rooms:room:manage',
  manageReports: 'reports:report:manage',
  manageSettings: 'settings:config:manage',
  manageWebsite: 'website:content:manage',
  manageAi: 'ai:assistant:manage',
} as const;

export type PermissionKey =
  | (typeof MENU_PERMISSIONS)[keyof typeof MENU_PERMISSIONS]
  | (typeof MANAGEMENT_PERMISSIONS)[keyof typeof MANAGEMENT_PERMISSIONS]
  | `${string}:${string}:${string}`;

/** Default role → permission mapping (seed reference) */
export const ROLE_PERMISSION_MATRIX: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: [
    ...Object.values(MENU_PERMISSIONS),
    ...Object.values(MANAGEMENT_PERMISSIONS),
    'frontdesk:operations:read',
    'frontdesk:operations:create',
    'frontdesk:operations:update',
    'procurement:order:read',
    'procurement:order:create',
    'procurement:order:update',
    'procurement:order:approve',
    'procurement:vendor:read',
    'procurement:vendor:manage',
    'maintenance:asset:read',
    'maintenance:asset:manage',
    'maintenance:workorder:read',
    'maintenance:workorder:manage',
    'finance:ledger:read',
    'finance:ledger:manage',
    'finance:journal:create',
    'finance:journal:approve',
    'finance:payment:approve',
    'finance:report:read',
    'events:lead:read',
    'events:lead:create',
    'events:lead:update',
    'events:lead:manage',
    'events:booking:read',
    'events:booking:manage',
    'corp-sales:lead:read',
    'corp-sales:lead:create',
    'corp-sales:lead:update',
    'corp-sales:lead:manage',
    'corp-sales:company:read',
    'corp-sales:company:manage',
    'corp-sales:contract:read',
    'corp-sales:contract:manage',
    'travel-desk:trip:read',
    'travel-desk:trip:create',
    'travel-desk:trip:update',
    'travel-desk:trip:manage',
    'travel-desk:vehicle:read',
    'travel-desk:vehicle:manage',
    'travel-desk:driver:read',
    'travel-desk:driver:manage',
    'travel-desk:dispatch:read',
    'travel-desk:dispatch:manage',
    'travel-desk:report:read',
  ] as PermissionKey[],
  HOTEL_OWNER: [
    ...Object.values(MENU_PERMISSIONS),
    ...Object.values(MANAGEMENT_PERMISSIONS),
    'frontdesk:operations:read',
    'frontdesk:operations:create',
    'frontdesk:operations:update',
    'procurement:order:read',
    'procurement:order:create',
    'procurement:order:update',
    'procurement:order:approve',
    'procurement:vendor:read',
    'procurement:vendor:manage',
    'maintenance:asset:read',
    'maintenance:asset:manage',
    'maintenance:workorder:read',
    'maintenance:workorder:manage',
    'finance:ledger:read',
    'finance:ledger:manage',
    'finance:journal:create',
    'finance:journal:approve',
    'finance:payment:approve',
    'finance:report:read',
    'events:lead:read',
    'events:lead:create',
    'events:lead:update',
    'events:lead:manage',
    'events:booking:read',
    'events:booking:manage',
    'corp-sales:lead:read',
    'corp-sales:lead:create',
    'corp-sales:lead:update',
    'corp-sales:lead:manage',
    'corp-sales:company:read',
    'corp-sales:company:manage',
    'corp-sales:contract:read',
    'corp-sales:contract:manage',
    'travel-desk:trip:read',
    'travel-desk:trip:create',
    'travel-desk:trip:update',
    'travel-desk:trip:manage',
    'travel-desk:vehicle:read',
    'travel-desk:vehicle:manage',
    'travel-desk:driver:read',
    'travel-desk:driver:manage',
    'travel-desk:dispatch:read',
    'travel-desk:dispatch:manage',
    'travel-desk:report:read',
  ] as PermissionKey[],
  GENERAL_MANAGER: [
    ...Object.values(MENU_PERMISSIONS),
    MANAGEMENT_PERMISSIONS.manageUsers,
    MANAGEMENT_PERMISSIONS.manageReservations,
    MANAGEMENT_PERMISSIONS.manageRooms,
    MANAGEMENT_PERMISSIONS.manageReports,
    MANAGEMENT_PERMISSIONS.manageEvents,
    MANAGEMENT_PERMISSIONS.manageCorpSales,
    MANAGEMENT_PERMISSIONS.manageTravelDesk,
    'frontdesk:operations:read',
    'frontdesk:operations:create',
    'frontdesk:operations:update',
    'gxp:portal:read',
    'gxp:portal:create',
    'gxp:portal:update',
  ],
  RECEPTIONIST: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.frontdesk,
    MENU_PERMISSIONS.reservations,
    MENU_PERMISSIONS.rooms,
    MENU_PERMISSIONS.crm,
    MENU_PERMISSIONS.events,
    MENU_PERMISSIONS.travelDesk,
    'frontdesk:operations:read',
    'frontdesk:operations:create',
    'frontdesk:operations:update',
    'travel-desk:trip:read',
    'travel-desk:trip:create',
    'travel-desk:trip:update',
    'travel-desk:dispatch:read',
  ],
  HOUSEKEEPING: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.housekeeping,
    MENU_PERMISSIONS.maintenance,
    MENU_PERMISSIONS.rooms,
    'housekeeping:task:read',
    'housekeeping:task:create',
    'housekeeping:task:update',
    'maintenance:asset:read',
    'maintenance:workorder:read',
    'maintenance:workorder:create',
  ],
  RESTAURANT_MANAGER: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.restaurant,
    MENU_PERMISSIONS.reports,
    'restaurant:order:read',
    'restaurant:order:create',
    'restaurant:order:update',
  ],
  KITCHEN_STAFF: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.restaurant,
    'restaurant:order:read',
    'restaurant:order:update',
  ],
  FINANCE: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.finance,
    MENU_PERMISSIONS.reports,
    MENU_PERMISSIONS.procurement,
    'finance:ledger:read',
    'finance:ledger:manage',
    'finance:journal:create',
    'finance:journal:approve',
    'finance:payment:approve',
    'finance:report:read',
    'procurement:order:read',
  ],
  INVENTORY_MANAGER: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.inventory,
    MENU_PERMISSIONS.procurement,
    MENU_PERMISSIONS.reports,
    'inventory:stock:read',
    'inventory:stock:manage',
    'inventory:stock:create',
    'inventory:stock:update',
    'inventory:stock:approve',
    'procurement:order:read',
    'procurement:order:create',
    'procurement:order:update',
    'procurement:order:approve',
    'procurement:vendor:read',
    'procurement:vendor:manage',
  ],
  STORE_MANAGER: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.procurement,
    MENU_PERMISSIONS.inventory,
    MENU_PERMISSIONS.reports,
    'procurement:order:read',
    'procurement:order:create',
    'procurement:order:update',
    'procurement:order:approve',
    'procurement:vendor:read',
    'procurement:vendor:manage',
    'inventory:stock:read',
  ],
  HR: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.hr,
    MENU_PERMISSIONS.reports,
    MANAGEMENT_PERMISSIONS.managePayroll,
    MANAGEMENT_PERMISSIONS.manageHr,
    MANAGEMENT_PERMISSIONS.manageUsers,
    'payroll:salary:read',
    'payroll:salary:manage',
    'users:user:read',
    'users:user:manage',
    'hr:employee:read',
    'hr:employee:manage',
  ],
  MARKETING: [
    MENU_PERMISSIONS.dashboard,
    MENU_PERMISSIONS.crm,
    MENU_PERMISSIONS.corpSales,
    MENU_PERMISSIONS.reports,
    MANAGEMENT_PERMISSIONS.manageCrm,
    MANAGEMENT_PERMISSIONS.manageCorpSales,
    'crm:lead:read',
    'crm:lead:create',
    'crm:lead:update',
    'crm:lead:manage',
    'corp-sales:lead:read',
    'corp-sales:lead:create',
    'corp-sales:lead:update',
    'corp-sales:lead:manage',
    'corp-sales:company:read',
    'corp-sales:company:manage',
    'corp-sales:contract:read',
    'corp-sales:contract:manage',
    'ai:assistant:read',
  ],
  GUEST: [MENU_PERMISSIONS.dashboard],
  CORPORATE_CLIENT: [MENU_PERMISSIONS.dashboard, MENU_PERMISSIONS.reservations],
};
