const BASE = '/corporate-sales';

export const CORP_SALES_ROUTES = {
  home: '/app/corporate-sales',
  companies: '/app/corporate-sales/companies',
  accounts: '/app/corporate-sales/accounts',
  leads: '/app/corporate-sales/leads',
  pipeline: '/app/corporate-sales/pipeline',
  contracts: '/app/corporate-sales/contracts',
  rates: '/app/corporate-sales/rates',
  roomAllocation: '/app/corporate-sales/room-allocation',
  bookings: '/app/corporate-sales/bookings',
  portal: '/app/corporate-sales/portal',
  employees: '/app/corporate-sales/employees',
  travelDesk: '/app/corporate-sales/travel-desk',
  approvals: '/app/corporate-sales/approvals',
  billing: '/app/corporate-sales/billing',
  credit: '/app/corporate-sales/credit',
  collections: '/app/corporate-sales/collections',
  meetings: '/app/corporate-sales/meetings',
  tasks: '/app/corporate-sales/tasks',
  renewals: '/app/corporate-sales/renewals',
  documents: '/app/corporate-sales/documents',
  targets: '/app/corporate-sales/targets',
  commissions: '/app/corporate-sales/commissions',
  owner: '/app/corporate-sales/owner',
  analytics: '/app/corporate-sales/analytics',
  reports: '/app/corporate-sales/reports',
  notifications: '/app/corporate-sales/notifications',
  mobile: '/app/corporate-sales/mobile',
  ai: '/app/corporate-sales/ai',
} as const;

export const CORP_SALES_API = {
  dashboard: `${BASE}/dashboard`,
  ownerDashboard: `${BASE}/owner-dashboard`,
  analytics: `${BASE}/analytics`,
  seed: `${BASE}/seed`,
  companies: `${BASE}/companies`,
  accounts: `${BASE}/accounts`,
  leads: `${BASE}/leads`,
  leadStatus: (id: string) => `${BASE}/leads/${id}/status`,
  pipeline: `${BASE}/pipeline`,
  contracts: `${BASE}/contracts`,
  rates: `${BASE}/rates`,
  roomAllocation: `${BASE}/room-allocation`,
  bookings: `${BASE}/bookings`,
  employees: `${BASE}/employees`,
  meetings: `${BASE}/meetings`,
  tasks: `${BASE}/tasks`,
  billing: `${BASE}/billing`,
  credit: `${BASE}/credit`,
  collections: `${BASE}/collections`,
  renewals: `${BASE}/renewals`,
  documents: `${BASE}/documents`,
  targets: `${BASE}/targets`,
  commissions: `${BASE}/commissions`,
  approvals: `${BASE}/approvals`,
  report: (type: string) => `${BASE}/reports/${type}`,
} as const;

export const CORP_SALES_NAV = [
  { label: 'Dashboard', href: CORP_SALES_ROUTES.home },
  { label: 'Companies', href: CORP_SALES_ROUTES.companies },
  { label: 'Key Accounts', href: CORP_SALES_ROUTES.accounts },
  { label: 'Leads', href: CORP_SALES_ROUTES.leads },
  { label: 'Pipeline', href: CORP_SALES_ROUTES.pipeline },
  { label: 'Contracts', href: CORP_SALES_ROUTES.contracts },
  { label: 'Rates', href: CORP_SALES_ROUTES.rates },
  { label: 'Room Allocation', href: CORP_SALES_ROUTES.roomAllocation },
  { label: 'Bookings', href: CORP_SALES_ROUTES.bookings },
  { label: 'Portal', href: CORP_SALES_ROUTES.portal },
  { label: 'Employees', href: CORP_SALES_ROUTES.employees },
  { label: 'Travel Desk', href: CORP_SALES_ROUTES.travelDesk },
  { label: 'Approvals', href: CORP_SALES_ROUTES.approvals },
  { label: 'Billing', href: CORP_SALES_ROUTES.billing },
  { label: 'Credit', href: CORP_SALES_ROUTES.credit },
  { label: 'Collections', href: CORP_SALES_ROUTES.collections },
  { label: 'Meetings', href: CORP_SALES_ROUTES.meetings },
  { label: 'Tasks', href: CORP_SALES_ROUTES.tasks },
  { label: 'Renewals', href: CORP_SALES_ROUTES.renewals },
  { label: 'Documents', href: CORP_SALES_ROUTES.documents },
  { label: 'Targets', href: CORP_SALES_ROUTES.targets },
  { label: 'Commissions', href: CORP_SALES_ROUTES.commissions },
  { label: 'Owner', href: CORP_SALES_ROUTES.owner },
  { label: 'Analytics', href: CORP_SALES_ROUTES.analytics },
  { label: 'Reports', href: CORP_SALES_ROUTES.reports },
  { label: 'Notifications', href: CORP_SALES_ROUTES.notifications },
  { label: 'Mobile', href: CORP_SALES_ROUTES.mobile },
  { label: 'AI', href: CORP_SALES_ROUTES.ai },
] as const;

export function isCorpSalesRoute(pathname: string): boolean {
  return pathname === '/app/corporate-sales' || pathname.startsWith('/app/corporate-sales/');
}
