services:
  nginx:
    image: nginx:1.27-alpine
    container_name: tungaos-nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: tungaos-api
    restart: always
    env_file:
      - ../apps/api/.env
    expose:
      - '4000'
