const BASE = '/hr';

export const HR_ROUTES = {
  home: '/app/hr',
  employees: '/app/hr/employees',
  organization: '/app/hr/organization',
  recruitment: '/app/hr/recruitment',
  onboarding: '/app/hr/onboarding',
  attendance: '/app/hr/attendance',
  shifts: '/app/hr/shifts',
  roster: '/app/hr/roster',
  leave: '/app/hr/leave',
  payroll: '/app/hr/payroll',
  performance: '/app/hr/performance',
  appraisals: '/app/hr/appraisals',
  training: '/app/hr/training',
  documents: '/app/hr/documents',
  expenses: '/app/hr/expenses',
  uniform: '/app/hr/uniform',
  ess: '/app/hr/ess',
  mss: '/app/hr/mss',
  exit: '/app/hr/exit',
  analytics: '/app/hr/analytics',
  owner: '/app/hr/owner',
  reports: '/app/hr/reports',
  mobile: '/app/hr/mobile',
  ai: '/app/hr/ai',
} as const;

export const HR_API = {
  dashboard: `${BASE}/dashboard`,
  ownerDashboard: `${BASE}/owner-dashboard`,
  analytics: `${BASE}/analytics`,
  seed: `${BASE}/seed`,
  employees: `${BASE}/employees`,
  departments: `${BASE}/departments`,
  designations: `${BASE}/designations`,
  attendance: `${BASE}/attendance`,
  leave: `${BASE}/leave`,
  leaveApprove: (id: string) => `${BASE}/leave/${id}/approve`,
  shifts: `${BASE}/shifts`,
  roster: `${BASE}/roster`,
  payrollRuns: `${BASE}/payroll/runs`,
  payrollCalculate: (id: string) => `${BASE}/payroll/runs/${id}/calculate`,
  payrollApprove: (id: string) => `${BASE}/payroll/runs/${id}/approve`,
  payrollComponents: `${BASE}/payroll/components`,
  jobOpenings: `${BASE}/recruitment/openings`,
  candidates: `${BASE}/recruitment/candidates`,
  interviews: `${BASE}/recruitment/interviews`,
  onboarding: `${BASE}/onboarding`,
  training: `${BASE}/training`,
  performance: `${BASE}/performance`,
  expenses: `${BASE}/expenses`,
  expenseApprove: (id: string) => `${BASE}/expenses/${id}/approve`,
  exit: `${BASE}/exit`,
  documents: `${BASE}/documents`,
  report: (type: string) => `${BASE}/reports/${type}`,
} as const;

export const HR_NAV = [
  { label: 'Dashboard', href: HR_ROUTES.home },
  { label: 'Employees', href: HR_ROUTES.employees },
  { label: 'Organization', href: HR_ROUTES.organization },
  { label: 'Recruitment', href: HR_ROUTES.recruitment },
  { label: 'Onboarding', href: HR_ROUTES.onboarding },
  { label: 'Attendance', href: HR_ROUTES.attendance },
  { label: 'Shifts', href: HR_ROUTES.shifts },
  { label: 'Roster', href: HR_ROUTES.roster },
  { label: 'Leave', href: HR_ROUTES.leave },
  { label: 'Payroll', href: HR_ROUTES.payroll },
  { label: 'Performance', href: HR_ROUTES.performance },
  { label: 'Appraisals', href: HR_ROUTES.appraisals },
  { label: 'Training', href: HR_ROUTES.training },
  { label: 'Documents', href: HR_ROUTES.documents },
  { label: 'Expenses', href: HR_ROUTES.expenses },
  { label: 'ESS', href: HR_ROUTES.ess },
  { label: 'MSS', href: HR_ROUTES.mss },
  { label: 'Exit', href: HR_ROUTES.exit },
  { label: 'Analytics', href: HR_ROUTES.analytics },
  { label: 'Owner', href: HR_ROUTES.owner },
  { label: 'Reports', href: HR_ROUTES.reports },
  { label: 'Mobile', href: HR_ROUTES.mobile },
  { label: 'AI', href: HR_ROUTES.ai },
] as const;

export function isHrRoute(pathname: string): boolean {
  return pathname === '/app/hr' || pathname.startsWith('/app/hr/');
}
