const BASE = '/front-desk';

export const FRONT_DESK_API = {
  dashboard: `${BASE}/dashboard`,
  performance: `${BASE}/performance`,
  arrivals: `${BASE}/arrivals`,
  departures: `${BASE}/departures`,
  walkIn: `${BASE}/walk-in`,
  assignRoom: `${BASE}/assign-room`,
  roomSuggestions: (reservationId: string) => `${BASE}/room-suggestions/${reservationId}`,
  folio: (reservationId: string) => `${BASE}/folio/${reservationId}`,
  payments: `${BASE}/payments`,
  checkInStart: (id: string) => `${BASE}/check-in/${id}/start`,
  checkInStep: (id: string) => `${BASE}/check-in/${id}/step`,
  checkOut: (id: string) => `${BASE}/check-out/${id}`,
  checkOutComplete: (id: string) => `${BASE}/check-out/${id}/complete`,
  calendar: `${BASE}/calendar`,
  search: `${BASE}/search`,
  complaints: `${BASE}/complaints`,
  guestRequests: `${BASE}/guest-requests`,
  tasks: `${BASE}/tasks`,
  lostFound: `${BASE}/lost-found`,
  communications: `${BASE}/communications`,
  keyCards: `${BASE}/key-cards`,
  deactivateKey: (id: string) => `${BASE}/key-cards/${id}/deactivate`,
} as const;

export const FRONT_DESK_ROUTES = {
  home: '/app/front-desk',
  arrivals: '/app/front-desk/arrivals',
  departures: '/app/front-desk/departures',
  walkIn: '/app/front-desk/walk-in',
  roomAssignment: '/app/front-desk/room-assignment',
  folio: (id: string) => `/app/front-desk/folio/${id}`,
  payments: '/app/front-desk/payments',
  checkIn: '/app/front-desk/check-in',
  checkOut: '/app/front-desk/check-out',
  communications: '/app/front-desk/communications',
  complaints: '/app/front-desk/complaints',
  tasks: '/app/front-desk/tasks',
  lostFound: '/app/front-desk/lost-found',
  keyCards: '/app/front-desk/key-cards',
  calendar: '/app/front-desk/calendar',
  search: '/app/front-desk/search',
  performance: '/app/front-desk/performance',
  guest: (id: string) => `/app/front-desk/guests/${id}`,
} as const;
