/**
 * Enterprise application navigation — sidebar, command palette, breadcrumbs.
 * All app routes live under /app/* to avoid conflicts with the public marketing site.
 */

import type { ModuleIconKey } from '@/icons/module-icons';

export const APP_BASE = '/app' as const;

export type AppRole =
  | 'SUPER_ADMIN'
  | 'HOTEL_OWNER'
  | 'GENERAL_MANAGER'
  | 'RECEPTIONIST'
  | 'HOUSEKEEPING'
  | 'FINANCE'
  | 'RESTAURANT_MANAGER'
  | 'INVENTORY_MANAGER'
  | 'HR'
  | 'MARKETING';

export interface NavItem {
  id: string;
  key: ModuleIconKey | string;
  label: string;
  href: string;
  permission?: string;
  roles?: AppRole[];
  badge?: string | number;
  favorite?: boolean;
  keywords?: string[];
  children?: NavItem[];
}

const p = (path: string) => `${APP_BASE}${path}`;

export const APP_NAVIGATION: NavItem[] = [
  { id: 'dashboard', key: 'dashboard', label: 'Command Center', href: p('/dashboard'), permission: 'dashboard:overview:read', keywords: ['home', 'overview', 'executive', 'owner', 'bi'] },
  {
    id: 'front-desk',
    key: 'reservations',
    label: 'Front Desk',
    href: p('/front-desk'),
    permission: 'frontdesk:operations:read',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'RECEPTIONIST'],
    badge: 'Live',
    keywords: ['reception', 'check-in', 'checkout', 'arrival', 'departure', 'walk-in'],
    children: [
      { id: 'fd-dash', key: 'dashboard', label: 'Operations Dashboard', href: p('/front-desk'), permission: 'frontdesk:operations:read' },
      { id: 'fd-arrivals', key: 'reservations', label: 'Arrival Board', href: p('/front-desk/arrivals'), permission: 'frontdesk:operations:read' },
      { id: 'fd-departures', key: 'reservations', label: 'Departure Board', href: p('/front-desk/departures'), permission: 'frontdesk:operations:read' },
      { id: 'fd-walkin', key: 'reservations', label: 'Walk-in Guest', href: p('/front-desk/walk-in'), permission: 'frontdesk:operations:create' },
      { id: 'fd-assign', key: 'rooms', label: 'Room Assignment', href: p('/front-desk/room-assignment'), permission: 'frontdesk:operations:update' },
      { id: 'fd-checkin', key: 'reservations', label: 'Check-in', href: p('/front-desk/check-in'), permission: 'frontdesk:operations:update' },
      { id: 'fd-checkout', key: 'reservations', label: 'Check-out', href: p('/front-desk/check-out'), permission: 'frontdesk:operations:update' },
      { id: 'fd-payments', key: 'finance', label: 'Payments', href: p('/front-desk/payments'), permission: 'frontdesk:operations:update' },
      { id: 'fd-comms', key: 'notifications', label: 'Communications', href: p('/front-desk/communications'), permission: 'frontdesk:operations:read' },
      { id: 'fd-complaints', key: 'notifications', label: 'Complaints', href: p('/front-desk/complaints'), permission: 'frontdesk:operations:read' },
      { id: 'fd-tasks', key: 'concierge', label: 'Tasks', href: p('/front-desk/tasks'), permission: 'frontdesk:operations:read' },
      { id: 'fd-lost', key: 'concierge', label: 'Lost & Found', href: p('/front-desk/lost-found'), permission: 'frontdesk:operations:read' },
      { id: 'fd-keys', key: 'hotel', label: 'Key Cards', href: p('/front-desk/key-cards'), permission: 'frontdesk:operations:read' },
      { id: 'fd-calendar', key: 'reservations', label: 'Calendar', href: p('/front-desk/calendar'), permission: 'frontdesk:operations:read' },
      { id: 'fd-search', key: 'concierge', label: 'Search', href: p('/front-desk/search'), permission: 'frontdesk:operations:read' },
      { id: 'fd-perf', key: 'reports', label: 'Performance', href: p('/front-desk/performance'), permission: 'frontdesk:operations:read' },
    ],
  },
  {
    id: 'reservations', key: 'reservations', label: 'Reservations', href: p('/reservations'), permission: 'reservations:booking:read', badge: 3,
    children: [
      { id: 'res-list', key: 'reservations', label: 'All Bookings', href: p('/reservations'), permission: 'reservations:booking:read' },
      { id: 'res-new', key: 'reservations', label: 'New Reservation', href: p('/reservations/new'), permission: 'reservations:booking:create' },
      { id: 'res-calendar', key: 'reservations', label: 'Calendar', href: p('/reservations/calendar'), permission: 'reservations:booking:read' },
    ],
  },
  {
    id: 'rooms',
    key: 'rooms',
    label: 'Rooms',
    href: p('/rooms'),
    permission: 'rooms:room:read',
    badge: 'Live',
    keywords: ['room', 'inventory', 'occupancy', 'allocation', 'digital twin'],
    children: [
      { id: 'rm-dash', key: 'rooms', label: 'Dashboard', href: p('/rooms'), permission: 'rooms:room:read' },
      { id: 'rm-board', key: 'rooms', label: 'Status Board', href: p('/rooms/board'), permission: 'rooms:room:read' },
      { id: 'rm-inv', key: 'rooms', label: 'Property Setup', href: p('/rooms/inventory'), permission: 'rooms:room:read' },
      { id: 'rm-cal', key: 'reservations', label: 'Calendar', href: p('/rooms/calendar'), permission: 'rooms:room:read' },
      { id: 'rm-alloc', key: 'rooms', label: 'Allocation', href: p('/rooms/allocation'), permission: 'rooms:room:update' },
      { id: 'rm-price', key: 'finance', label: 'Pricing', href: p('/rooms/pricing'), permission: 'rooms:room:read' },
      { id: 'rm-rev', key: 'finance', label: 'Revenue', href: p('/rooms/revenue'), permission: 'reports:report:read' },
      { id: 'rm-assets', key: 'inventory', label: 'Assets', href: p('/rooms/assets'), permission: 'rooms:room:read' },
      { id: 'rm-maint', key: 'housekeeping', label: 'Maintenance', href: p('/rooms/maintenance'), permission: 'rooms:room:read' },
      { id: 'rm-blocks', key: 'rooms', label: 'Blocks', href: p('/rooms/blocks'), permission: 'rooms:room:update' },
      { id: 'rm-insp', key: 'reports', label: 'Inspection', href: p('/rooms/inspection'), permission: 'rooms:room:read' },
      { id: 'rm-amen', key: 'rooms', label: 'Amenities', href: p('/rooms/amenities'), permission: 'rooms:room:read' },
      { id: 'rm-reports', key: 'reports', label: 'Reports', href: p('/rooms/reports'), permission: 'reports:report:read' },
      { id: 'rm-search', key: 'concierge', label: 'Search', href: p('/rooms/search'), permission: 'rooms:room:read' },
    ],
  },
  {
    id: 'housekeeping',
    key: 'housekeeping',
    label: 'Housekeeping',
    href: p('/housekeeping'),
    permission: 'housekeeping:task:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'HOUSEKEEPING'],
    keywords: ['cleaning', 'laundry', 'linen', 'inspection', 'hk'],
    children: [
      { id: 'hk-dash', key: 'housekeeping', label: 'Dashboard', href: p('/housekeeping'), permission: 'housekeeping:task:read' },
      { id: 'hk-tasks', key: 'housekeeping', label: 'Cleaning Tasks', href: p('/housekeeping/tasks'), permission: 'housekeeping:task:read' },
      { id: 'hk-mobile', key: 'housekeeping', label: 'Staff Mobile', href: p('/housekeeping/mobile'), permission: 'housekeeping:task:read' },
      { id: 'hk-insp', key: 'housekeeping', label: 'Inspection', href: p('/housekeeping/inspection'), permission: 'housekeeping:task:read' },
      { id: 'hk-laundry', key: 'housekeeping', label: 'Laundry', href: p('/housekeeping/laundry'), permission: 'housekeeping:task:read' },
      { id: 'hk-linen', key: 'housekeeping', label: 'Linen Inventory', href: p('/housekeeping/linen'), permission: 'housekeeping:task:read' },
      { id: 'hk-lost', key: 'housekeeping', label: 'Lost & Found', href: p('/housekeeping/lost-found'), permission: 'housekeeping:task:read' },
      { id: 'hk-req', key: 'housekeeping', label: 'Guest Requests', href: p('/housekeeping/guest-requests'), permission: 'housekeeping:task:read' },
      { id: 'hk-staff', key: 'housekeeping', label: 'Staff', href: p('/housekeeping/staff'), permission: 'housekeeping:task:read' },
      { id: 'hk-deep', key: 'housekeeping', label: 'Deep Cleaning', href: p('/housekeeping/deep-cleaning'), permission: 'housekeeping:task:read' },
      { id: 'hk-reports', key: 'reports', label: 'Reports', href: p('/housekeeping/reports'), permission: 'housekeeping:task:read' },
    ],
  },
  {
    id: 'gxp',
    key: 'concierge',
    label: 'Guest Experience',
    href: p('/gxp'),
    permission: 'gxp:portal:read',
    badge: 'Live',
    keywords: ['gxp', 'guest portal', 'qr', 'concierge', 'digital key', 'pwa'],
    children: [
      { id: 'gxp-dash', key: 'concierge', label: 'Dashboard', href: p('/gxp'), permission: 'gxp:portal:read' },
      { id: 'gxp-qr', key: 'concierge', label: 'Room QR Codes', href: p('/gxp/qr-codes'), permission: 'gxp:portal:read' },
      { id: 'gxp-req', key: 'concierge', label: 'Guest Requests', href: p('/gxp/requests'), permission: 'gxp:portal:read' },
      { id: 'gxp-offers', key: 'concierge', label: 'Offers', href: p('/gxp/offers'), permission: 'gxp:portal:read' },
      { id: 'gxp-ann', key: 'concierge', label: 'Announcements', href: p('/gxp/announcements'), permission: 'gxp:portal:read' },
      { id: 'gxp-reports', key: 'reports', label: 'Reports', href: p('/gxp/reports'), permission: 'gxp:portal:read' },
    ],
  },
  {
    id: 'restaurant',
    key: 'restaurant',
    label: 'Restaurant POS',
    href: p('/restaurant'),
    permission: 'restaurant:order:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'RESTAURANT_MANAGER'],
    keywords: ['pos', 'fnb', 'kitchen', 'kds', 'menu', 'billing', 'bar', 'room service'],
    children: [
      { id: 'fnb-dash', key: 'restaurant', label: 'Dashboard', href: p('/restaurant'), permission: 'restaurant:order:read' },
      { id: 'fnb-pos', key: 'restaurant', label: 'Point of Sale', href: p('/restaurant/pos'), permission: 'restaurant:order:create' },
      { id: 'fnb-tables', key: 'restaurant', label: 'Table Map', href: p('/restaurant/tables'), permission: 'restaurant:order:read' },
      { id: 'fnb-menu', key: 'restaurant', label: 'Menu Builder', href: p('/restaurant/menu'), permission: 'restaurant:order:read' },
      { id: 'kitchen', key: 'restaurant', label: 'Kitchen (KDS)', href: p('/kitchen'), permission: 'restaurant:order:read' },
      { id: 'fnb-billing', key: 'finance', label: 'Billing', href: p('/restaurant/billing'), permission: 'restaurant:order:read' },
      { id: 'fnb-rs', key: 'restaurant', label: 'Room Service', href: p('/restaurant/room-service'), permission: 'restaurant:order:create' },
      { id: 'fnb-bar', key: 'restaurant', label: 'Bar Management', href: p('/restaurant/bar'), permission: 'restaurant:order:read' },
      { id: 'fnb-qr', key: 'restaurant', label: 'QR Menu', href: p('/restaurant/qr-menu'), permission: 'restaurant:order:read' },
      { id: 'fnb-waiter', key: 'restaurant', label: 'Waiter Mobile', href: p('/restaurant/waiter'), permission: 'restaurant:order:read' },
      { id: 'fnb-outlets', key: 'restaurant', label: 'Outlets', href: p('/restaurant/outlets'), permission: 'restaurant:order:read' },
      { id: 'fnb-reports', key: 'reports', label: 'Reports', href: p('/restaurant/reports'), permission: 'restaurant:order:read' },
    ],
  },
  {
    id: 'inventory',
    key: 'inventory',
    label: 'Inventory',
    href: p('/inventory'),
    permission: 'inventory:stock:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'INVENTORY_MANAGER'],
    keywords: ['stock', 'store', 'warehouse', 'consumption', 'barcode', 'batch', 'expiry'],
    children: [
      { id: 'inv-dash', key: 'inventory', label: 'Dashboard', href: p('/inventory'), permission: 'inventory:stock:read' },
      { id: 'inv-stores', key: 'inventory', label: 'Stores', href: p('/inventory/stores'), permission: 'inventory:stock:read' },
      { id: 'inv-items', key: 'inventory', label: 'Item Master', href: p('/inventory/items'), permission: 'inventory:stock:read' },
      { id: 'inv-stock', key: 'inventory', label: 'Stock', href: p('/inventory/stock'), permission: 'inventory:stock:read' },
      { id: 'inv-move', key: 'inventory', label: 'Movements', href: p('/inventory/movements'), permission: 'inventory:stock:read' },
      { id: 'inv-issue', key: 'inventory', label: 'Issues', href: p('/inventory/issues'), permission: 'inventory:stock:read' },
      { id: 'inv-transfer', key: 'inventory', label: 'Transfers', href: p('/inventory/transfers'), permission: 'inventory:stock:read' },
      { id: 'inv-consume', key: 'inventory', label: 'Consumption', href: p('/inventory/consumption'), permission: 'inventory:stock:read' },
      { id: 'inv-batch', key: 'inventory', label: 'Batches', href: p('/inventory/batches'), permission: 'inventory:stock:read' },
      { id: 'inv-expiry', key: 'inventory', label: 'Expiry', href: p('/inventory/expiry'), permission: 'inventory:stock:read' },
      { id: 'inv-adj', key: 'inventory', label: 'Adjustments', href: p('/inventory/adjustments'), permission: 'inventory:stock:read' },
      { id: 'inv-audit', key: 'inventory', label: 'Audits', href: p('/inventory/audits'), permission: 'inventory:stock:read' },
      { id: 'inv-pr', key: 'inventory', label: 'Purchase Requests', href: p('/inventory/purchase-requests'), permission: 'inventory:stock:read' },
      { id: 'inv-scan', key: 'inventory', label: 'Scanner', href: p('/inventory/scanner'), permission: 'inventory:stock:read' },
      { id: 'inv-mobile', key: 'inventory', label: 'Mobile', href: p('/inventory/mobile'), permission: 'inventory:stock:read' },
      { id: 'inv-reports', key: 'reports', label: 'Reports', href: p('/inventory/reports'), permission: 'inventory:stock:read' },
      { id: 'inv-analytics', key: 'reports', label: 'Analytics', href: p('/inventory/analytics'), permission: 'inventory:stock:read' },
    ],
  },
  {
    id: 'procurement',
    key: 'finance',
    label: 'Procurement',
    href: p('/procurement'),
    permission: 'procurement:order:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'INVENTORY_MANAGER'],
    keywords: ['purchase', 'vendor', 'rfq', 'quotation', 'po', 'grn', 'procurement'],
    children: [
      { id: 'proc-dash', key: 'finance', label: 'Dashboard', href: p('/procurement'), permission: 'procurement:order:read' },
      { id: 'proc-vendors', key: 'finance', label: 'Vendors', href: p('/procurement/vendors'), permission: 'procurement:vendor:read' },
      { id: 'proc-pr', key: 'finance', label: 'Purchase Requests', href: p('/procurement/purchase-requests'), permission: 'procurement:order:read' },
      { id: 'proc-rfq', key: 'finance', label: 'RFQs', href: p('/procurement/rfqs'), permission: 'procurement:order:read' },
      { id: 'proc-quotes', key: 'finance', label: 'Quotations', href: p('/procurement/quotations'), permission: 'procurement:order:read' },
      { id: 'proc-compare', key: 'finance', label: 'Comparison', href: p('/procurement/comparison'), permission: 'procurement:order:read' },
      { id: 'proc-po', key: 'finance', label: 'Purchase Orders', href: p('/procurement/purchase-orders'), permission: 'procurement:order:read' },
      { id: 'proc-grn', key: 'finance', label: 'GRN', href: p('/procurement/grns'), permission: 'procurement:order:read' },
      { id: 'proc-insp', key: 'finance', label: 'Inspection', href: p('/procurement/inspection'), permission: 'procurement:order:read' },
      { id: 'proc-ret', key: 'finance', label: 'Returns', href: p('/procurement/returns'), permission: 'procurement:order:read' },
      { id: 'proc-con', key: 'finance', label: 'Contracts', href: p('/procurement/contracts'), permission: 'procurement:order:read' },
      { id: 'proc-budget', key: 'finance', label: 'Budgets', href: p('/procurement/budgets'), permission: 'procurement:order:read' },
      { id: 'proc-inv', key: 'finance', label: 'Invoices', href: p('/procurement/invoices'), permission: 'procurement:order:read' },
      { id: 'proc-approve', key: 'finance', label: 'Approvals', href: p('/procurement/approvals'), permission: 'procurement:order:approve' },
      { id: 'proc-reports', key: 'reports', label: 'Reports', href: p('/procurement/reports'), permission: 'procurement:order:read' },
      { id: 'proc-analytics', key: 'reports', label: 'Analytics', href: p('/procurement/analytics'), permission: 'procurement:order:read' },
      { id: 'proc-mobile', key: 'finance', label: 'Mobile', href: p('/procurement/mobile'), permission: 'procurement:order:read' },
    ],
  },
  {
    id: 'maintenance',
    key: 'housekeeping',
    label: 'Maintenance',
    href: p('/maintenance'),
    permission: 'maintenance:asset:read',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'HOUSEKEEPING', 'INVENTORY_MANAGER'],
    keywords: ['eam', 'cmms', 'asset', 'work order', 'preventive', 'amc', 'warranty'],
    children: [
      { id: 'eam-dash', key: 'housekeeping', label: 'Dashboard', href: p('/maintenance'), permission: 'maintenance:asset:read' },
      { id: 'eam-assets', key: 'housekeeping', label: 'Assets', href: p('/maintenance/assets'), permission: 'maintenance:asset:read' },
      { id: 'eam-wo', key: 'housekeeping', label: 'Work Orders', href: p('/maintenance/work-orders'), permission: 'maintenance:workorder:read' },
      { id: 'eam-req', key: 'housekeeping', label: 'Requests', href: p('/maintenance/requests'), permission: 'maintenance:workorder:read' },
      { id: 'eam-pm', key: 'housekeeping', label: 'Preventive', href: p('/maintenance/preventive'), permission: 'maintenance:asset:read' },
      { id: 'eam-corr', key: 'housekeeping', label: 'Corrective', href: p('/maintenance/corrective'), permission: 'maintenance:workorder:read' },
      { id: 'eam-amc', key: 'housekeeping', label: 'AMC', href: p('/maintenance/amc'), permission: 'maintenance:asset:read' },
      { id: 'eam-war', key: 'housekeeping', label: 'Warranty', href: p('/maintenance/warranty'), permission: 'maintenance:asset:read' },
      { id: 'eam-tech', key: 'housekeeping', label: 'Technicians', href: p('/maintenance/technicians'), permission: 'maintenance:workorder:read' },
      { id: 'eam-parts', key: 'housekeeping', label: 'Parts', href: p('/maintenance/parts'), permission: 'maintenance:workorder:read' },
      { id: 'eam-insp', key: 'housekeeping', label: 'Inspection', href: p('/maintenance/inspection'), permission: 'maintenance:asset:read' },
      { id: 'eam-safe', key: 'housekeeping', label: 'Safety', href: p('/maintenance/safety'), permission: 'maintenance:asset:read' },
      { id: 'eam-energy', key: 'housekeeping', label: 'Energy', href: p('/maintenance/energy'), permission: 'maintenance:asset:read' },
      { id: 'eam-rooms', key: 'housekeeping', label: 'Room Assets', href: p('/maintenance/rooms'), permission: 'maintenance:asset:read' },
      { id: 'eam-owner', key: 'housekeeping', label: 'Owner View', href: p('/maintenance/owner'), permission: 'maintenance:asset:read' },
      { id: 'eam-reports', key: 'reports', label: 'Reports', href: p('/maintenance/reports'), permission: 'maintenance:asset:read' },
      { id: 'eam-analytics', key: 'reports', label: 'Analytics', href: p('/maintenance/analytics'), permission: 'maintenance:asset:read' },
      { id: 'eam-scanner', key: 'housekeeping', label: 'Scanner', href: p('/maintenance/scanner'), permission: 'maintenance:asset:read' },
      { id: 'eam-mobile', key: 'housekeeping', label: 'Mobile', href: p('/maintenance/mobile'), permission: 'maintenance:workorder:read' },
    ],
  },
  {
    id: 'travel',
    key: 'concierge',
    label: 'Travel Desk',
    href: p('/travel-desk'),
    permission: 'travel-desk:trip:read',
    keywords: ['transport', 'fleet', 'airport', 'pickup', 'driver', 'vehicle', 'taxi', 'shuttle', 'dispatch'],
    children: [
      { id: 'td-dash', key: 'concierge', label: 'Dashboard', href: p('/travel-desk'), permission: 'travel-desk:trip:read' },
      { id: 'td-req', key: 'concierge', label: 'Travel Desk', href: p('/travel-desk/requests'), permission: 'travel-desk:trip:read' },
      { id: 'td-disp', key: 'concierge', label: 'Dispatch Center', href: p('/travel-desk/dispatch'), permission: 'travel-desk:dispatch:read' },
      { id: 'td-trips', key: 'concierge', label: 'Trips', href: p('/travel-desk/trips'), permission: 'travel-desk:trip:read' },
      { id: 'td-air', key: 'concierge', label: 'Airport Transfers', href: p('/travel-desk/airport'), permission: 'travel-desk:trip:read' },
      { id: 'td-corp', key: 'concierge', label: 'Corporate Transport', href: p('/travel-desk/corporate'), permission: 'travel-desk:trip:read' },
      { id: 'td-shut', key: 'concierge', label: 'Hotel Shuttle', href: p('/travel-desk/shuttle'), permission: 'travel-desk:trip:read' },
      { id: 'td-veh', key: 'concierge', label: 'Vehicles', href: p('/travel-desk/vehicles'), permission: 'travel-desk:vehicle:read' },
      { id: 'td-drv', key: 'concierge', label: 'Drivers', href: p('/travel-desk/drivers'), permission: 'travel-desk:driver:read' },
      { id: 'td-vend', key: 'concierge', label: 'Vendors', href: p('/travel-desk/vendors'), permission: 'travel-desk:trip:read' },
      { id: 'td-fuel', key: 'concierge', label: 'Fuel', href: p('/travel-desk/fuel'), permission: 'travel-desk:vehicle:read' },
      { id: 'td-maint', key: 'concierge', label: 'Maintenance', href: p('/travel-desk/maintenance'), permission: 'travel-desk:vehicle:read' },
      { id: 'td-gps', key: 'concierge', label: 'GPS Tracking', href: p('/travel-desk/gps'), permission: 'travel-desk:dispatch:read' },
      { id: 'td-bill', key: 'finance', label: 'Billing', href: p('/travel-desk/billing'), permission: 'travel-desk:trip:read' },
      { id: 'td-cal', key: 'concierge', label: 'Calendar', href: p('/travel-desk/calendar'), permission: 'travel-desk:trip:read' },
      { id: 'td-analytics', key: 'reports', label: 'Analytics', href: p('/travel-desk/analytics'), permission: 'travel-desk:report:read' },
      { id: 'td-reports', key: 'reports', label: 'Reports', href: p('/travel-desk/reports'), permission: 'travel-desk:report:read' },
      { id: 'td-owner', key: 'concierge', label: 'Owner View', href: p('/travel-desk/owner'), permission: 'travel-desk:trip:read' },
      { id: 'td-mobile', key: 'concierge', label: 'Mobile Apps', href: p('/travel-desk/mobile'), permission: 'travel-desk:trip:read' },
    ],
  },
  { id: 'parking', key: 'hotel', label: 'Parking', href: p('/parking'), permission: 'rooms:room:read' },
  {
    id: 'finance',
    key: 'finance',
    label: 'Finance',
    href: p('/finance'),
    permission: 'finance:ledger:read',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'FINANCE'],
    keywords: ['finance', 'accounting', 'ledger', 'gst', 'budget', 'revenue', 'expense'],
    children: [
      { id: 'fin-dash', key: 'finance', label: 'Dashboard', href: p('/finance'), permission: 'finance:ledger:read' },
      { id: 'fin-coa', key: 'finance', label: 'Chart of Accounts', href: p('/finance/chart-of-accounts'), permission: 'finance:ledger:read' },
      { id: 'fin-gl', key: 'finance', label: 'General Ledger', href: p('/finance/general-ledger'), permission: 'finance:ledger:read' },
      { id: 'fin-je', key: 'finance', label: 'Journal Entries', href: p('/finance/journal-entries'), permission: 'finance:journal:create' },
      { id: 'fin-ar', key: 'finance', label: 'Receivables', href: p('/finance/receivables'), permission: 'finance:ledger:read' },
      { id: 'fin-ap', key: 'finance', label: 'Payables', href: p('/finance/payables'), permission: 'finance:ledger:read' },
      { id: 'fin-rev', key: 'finance', label: 'Revenue', href: p('/finance/revenue'), permission: 'finance:ledger:read' },
      { id: 'fin-exp', key: 'finance', label: 'Expenses', href: p('/finance/expenses'), permission: 'finance:ledger:read' },
      { id: 'fin-bank', key: 'finance', label: 'Bank', href: p('/finance/bank'), permission: 'finance:ledger:read' },
      { id: 'fin-cash', key: 'finance', label: 'Cash', href: p('/finance/cash'), permission: 'finance:ledger:read' },
      { id: 'fin-gst', key: 'finance', label: 'GST', href: p('/finance/gst'), permission: 'finance:report:read' },
      { id: 'fin-tax', key: 'finance', label: 'Tax / TDS', href: p('/finance/tax'), permission: 'finance:report:read' },
      { id: 'fin-budget', key: 'finance', label: 'Budget', href: p('/finance/budget'), permission: 'finance:ledger:read' },
      { id: 'fin-cc', key: 'finance', label: 'Cost Centers', href: p('/finance/cost-centers'), permission: 'finance:ledger:read' },
      { id: 'fin-inv', key: 'finance', label: 'Invoices', href: p('/finance/invoices'), permission: 'finance:ledger:read' },
      { id: 'fin-audit', key: 'finance', label: 'Night Audit', href: p('/finance/night-audit'), permission: 'finance:ledger:read' },
      { id: 'fin-recon', key: 'finance', label: 'Reconciliation', href: p('/finance/reconciliation'), permission: 'finance:ledger:read' },
      { id: 'fin-dept', key: 'finance', label: 'Departments', href: p('/finance/departments'), permission: 'finance:report:read' },
      { id: 'fin-fa', key: 'finance', label: 'Fixed Assets', href: p('/finance/fixed-assets'), permission: 'finance:ledger:read' },
      { id: 'fin-reports', key: 'reports', label: 'Reports', href: p('/finance/reports'), permission: 'finance:report:read' },
      { id: 'fin-analytics', key: 'reports', label: 'Analytics', href: p('/finance/analytics'), permission: 'finance:report:read' },
      { id: 'fin-owner', key: 'finance', label: 'Owner View', href: p('/finance/owner'), permission: 'finance:ledger:read' },
      { id: 'fin-approve', key: 'finance', label: 'Approvals', href: p('/finance/approvals'), permission: 'finance:payment:approve' },
      { id: 'fin-mobile', key: 'finance', label: 'Mobile', href: p('/finance/mobile'), permission: 'finance:ledger:read' },
    ],
  },
  {
    id: 'hr',
    key: 'hr',
    label: 'HRMS',
    href: p('/hr'),
    permission: 'payroll:salary:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'HR', 'FINANCE'],
    keywords: ['hr', 'human resources', 'payroll', 'attendance', 'leave', 'recruitment', 'employee'],
    children: [
      { id: 'hr-dash', key: 'hr', label: 'Dashboard', href: p('/hr'), permission: 'payroll:salary:read' },
      { id: 'hr-emp', key: 'hr', label: 'Employees', href: p('/hr/employees'), permission: 'users:user:read' },
      { id: 'hr-org', key: 'hr', label: 'Organization', href: p('/hr/organization'), permission: 'payroll:salary:read' },
      { id: 'hr-recruit', key: 'hr', label: 'Recruitment', href: p('/hr/recruitment'), permission: 'payroll:salary:read' },
      { id: 'hr-onboard', key: 'hr', label: 'Onboarding', href: p('/hr/onboarding'), permission: 'payroll:salary:read' },
      { id: 'hr-att', key: 'hr', label: 'Attendance', href: p('/hr/attendance'), permission: 'payroll:salary:read' },
      { id: 'hr-shift', key: 'hr', label: 'Shifts', href: p('/hr/shifts'), permission: 'payroll:salary:read' },
      { id: 'hr-roster', key: 'hr', label: 'Roster', href: p('/hr/roster'), permission: 'payroll:salary:read' },
      { id: 'hr-leave', key: 'hr', label: 'Leave', href: p('/hr/leave'), permission: 'payroll:salary:read' },
      { id: 'hr-payroll', key: 'finance', label: 'Payroll', href: p('/hr/payroll'), permission: 'payroll:salary:read' },
      { id: 'hr-perf', key: 'hr', label: 'Performance', href: p('/hr/performance'), permission: 'payroll:salary:read' },
      { id: 'hr-appraisal', key: 'hr', label: 'Appraisals', href: p('/hr/appraisals'), permission: 'payroll:salary:read' },
      { id: 'hr-train', key: 'hr', label: 'Training', href: p('/hr/training'), permission: 'payroll:salary:read' },
      { id: 'hr-docs', key: 'documents', label: 'Documents', href: p('/hr/documents'), permission: 'payroll:salary:read' },
      { id: 'hr-exp', key: 'finance', label: 'Expenses', href: p('/hr/expenses'), permission: 'payroll:salary:read' },
      { id: 'hr-ess', key: 'hr', label: 'Employee Self Service', href: p('/hr/ess'), permission: 'payroll:salary:read' },
      { id: 'hr-mss', key: 'hr', label: 'Manager Portal', href: p('/hr/mss'), permission: 'payroll:salary:read' },
      { id: 'hr-exit', key: 'hr', label: 'Exit', href: p('/hr/exit'), permission: 'payroll:salary:read' },
      { id: 'hr-analytics', key: 'reports', label: 'Analytics', href: p('/hr/analytics'), permission: 'payroll:salary:read' },
      { id: 'hr-owner', key: 'hr', label: 'Owner View', href: p('/hr/owner'), permission: 'payroll:salary:read' },
      { id: 'hr-reports', key: 'reports', label: 'Reports', href: p('/hr/reports'), permission: 'reports:report:read' },
      { id: 'hr-mobile', key: 'hr', label: 'Mobile', href: p('/hr/mobile'), permission: 'payroll:salary:read' },
      { id: 'hr-ai', key: 'dashboard', label: 'AI Insights', href: p('/hr/ai'), permission: 'ai:assistant:read' },
    ],
  },
  {
    id: 'crm',
    key: 'crm',
    label: 'CRM & Loyalty',
    href: p('/crm'),
    permission: 'crm:lead:read',
    badge: 'Live',
    roles: ['SUPER_ADMIN', 'HOTEL_OWNER', 'GENERAL_MANAGER', 'MARKETING', 'RECEPTIONIST'],
    keywords: ['crm', 'guest', 'loyalty', 'marketing', 'campaign', 'referral', 'corporate'],
    children: [
      { id: 'crm-dash', key: 'crm', label: 'Dashboard', href: p('/crm'), permission: 'crm:lead:read' },
      { id: 'crm-guests', key: 'crm', label: 'Guest 360', href: p('/crm/guests'), permission: 'crm:lead:read' },
      { id: 'crm-seg', key: 'crm', label: 'Segments', href: p('/crm/segments'), permission: 'crm:lead:read' },
      { id: 'crm-leads', key: 'crm', label: 'Leads', href: p('/crm/leads'), permission: 'crm:lead:read' },
      { id: 'crm-pipe', key: 'crm', label: 'Pipeline', href: p('/crm/pipeline'), permission: 'crm:lead:read' },
      { id: 'crm-loyalty', key: 'crm', label: 'Loyalty', href: p('/crm/loyalty'), permission: 'crm:lead:read' },
      { id: 'crm-points', key: 'crm', label: 'Points', href: p('/crm/points'), permission: 'crm:lead:read' },
      { id: 'crm-corp', key: 'crm', label: 'Corporate', href: p('/crm/corporate'), permission: 'crm:lead:read' },
      { id: 'crm-ta', key: 'crm', label: 'Travel Agents', href: p('/crm/travel-agents'), permission: 'crm:lead:read' },
      { id: 'crm-camp', key: 'crm', label: 'Campaigns', href: p('/crm/campaigns'), permission: 'crm:lead:read' },
      { id: 'crm-email', key: 'crm', label: 'Email', href: p('/crm/email'), permission: 'crm:lead:read' },
      { id: 'crm-wa', key: 'crm', label: 'WhatsApp', href: p('/crm/whatsapp'), permission: 'crm:lead:read' },
      { id: 'crm-sms', key: 'crm', label: 'SMS', href: p('/crm/sms'), permission: 'crm:lead:read' },
      { id: 'crm-auto', key: 'crm', label: 'Automation', href: p('/crm/automation'), permission: 'crm:lead:read' },
      { id: 'crm-coupon', key: 'crm', label: 'Coupons', href: p('/crm/coupons'), permission: 'crm:lead:read' },
      { id: 'crm-gift', key: 'crm', label: 'Gift Cards', href: p('/crm/gift-cards'), permission: 'crm:lead:read' },
      { id: 'crm-ref', key: 'crm', label: 'Referrals', href: p('/crm/referrals'), permission: 'crm:lead:read' },
      { id: 'crm-fb', key: 'crm', label: 'Feedback', href: p('/crm/feedback'), permission: 'crm:lead:read' },
      { id: 'crm-rev', key: 'crm', label: 'Reviews', href: p('/crm/reviews'), permission: 'crm:lead:read' },
      { id: 'crm-upsell', key: 'crm', label: 'Upsell', href: p('/crm/upsell'), permission: 'crm:lead:read' },
      { id: 'crm-analytics', key: 'reports', label: 'Analytics', href: p('/crm/analytics'), permission: 'crm:lead:read' },
      { id: 'crm-owner', key: 'crm', label: 'Owner View', href: p('/crm/owner'), permission: 'crm:lead:read' },
      { id: 'crm-reports', key: 'reports', label: 'Reports', href: p('/crm/reports'), permission: 'reports:report:read' },
      { id: 'crm-mobile', key: 'crm', label: 'Mobile', href: p('/crm/mobile'), permission: 'crm:lead:read' },
      { id: 'crm-ai', key: 'dashboard', label: 'AI Insights', href: p('/crm/ai'), permission: 'ai:assistant:read' },
    ],
  },
  {
    id: 'corporate-sales',
    key: 'finance',
    label: 'Corporate Sales',
    href: p('/corporate-sales'),
    permission: 'corp-sales:company:read',
    keywords: ['b2b', 'corporate', 'contract', 'key account', 'sales pipeline', 'TMC'],
    children: [
      { id: 'cs-dash', key: 'finance', label: 'Dashboard', href: p('/corporate-sales'), permission: 'corp-sales:company:read' },
      { id: 'cs-co', key: 'finance', label: 'Companies', href: p('/corporate-sales/companies'), permission: 'corp-sales:company:read' },
      { id: 'cs-kam', key: 'crm', label: 'Key Accounts', href: p('/corporate-sales/accounts'), permission: 'corp-sales:company:read' },
      { id: 'cs-leads', key: 'crm', label: 'Leads', href: p('/corporate-sales/leads'), permission: 'corp-sales:lead:read' },
      { id: 'cs-pipe', key: 'crm', label: 'Pipeline', href: p('/corporate-sales/pipeline'), permission: 'corp-sales:lead:read' },
      { id: 'cs-contract', key: 'documents', label: 'Contracts', href: p('/corporate-sales/contracts'), permission: 'corp-sales:contract:read' },
      { id: 'cs-rates', key: 'finance', label: 'Rates', href: p('/corporate-sales/rates'), permission: 'corp-sales:contract:read' },
      { id: 'cs-alloc', key: 'rooms', label: 'Room Allocation', href: p('/corporate-sales/room-allocation'), permission: 'corp-sales:company:read' },
      { id: 'cs-book', key: 'reservations', label: 'Bookings', href: p('/corporate-sales/bookings'), permission: 'corp-sales:company:read' },
      { id: 'cs-portal', key: 'gxp', label: 'Corporate Portal', href: p('/corporate-sales/portal'), permission: 'corp-sales:company:read' },
      { id: 'cs-emp', key: 'crm', label: 'Employees', href: p('/corporate-sales/employees'), permission: 'corp-sales:company:read' },
      { id: 'cs-td', key: 'concierge', label: 'Travel Desk', href: p('/corporate-sales/travel-desk'), permission: 'corp-sales:company:read' },
      { id: 'cs-appr', key: 'finance', label: 'Approvals', href: p('/corporate-sales/approvals'), permission: 'corp-sales:contract:read' },
      { id: 'cs-bill', key: 'finance', label: 'Billing', href: p('/corporate-sales/billing'), permission: 'corp-sales:company:read' },
      { id: 'cs-credit', key: 'finance', label: 'Credit', href: p('/corporate-sales/credit'), permission: 'corp-sales:company:read' },
      { id: 'cs-coll', key: 'finance', label: 'Collections', href: p('/corporate-sales/collections'), permission: 'corp-sales:company:read' },
      { id: 'cs-meet', key: 'crm', label: 'Meetings', href: p('/corporate-sales/meetings'), permission: 'corp-sales:company:read' },
      { id: 'cs-tasks', key: 'housekeeping', label: 'Tasks', href: p('/corporate-sales/tasks'), permission: 'corp-sales:company:read' },
      { id: 'cs-renew', key: 'documents', label: 'Renewals', href: p('/corporate-sales/renewals'), permission: 'corp-sales:contract:read' },
      { id: 'cs-docs', key: 'documents', label: 'Documents', href: p('/corporate-sales/documents'), permission: 'corp-sales:company:read' },
      { id: 'cs-target', key: 'reports', label: 'Targets', href: p('/corporate-sales/targets'), permission: 'corp-sales:company:read' },
      { id: 'cs-comm', key: 'finance', label: 'Commissions', href: p('/corporate-sales/commissions'), permission: 'corp-sales:company:read' },
      { id: 'cs-owner', key: 'finance', label: 'Owner View', href: p('/corporate-sales/owner'), permission: 'corp-sales:company:read' },
      { id: 'cs-analytics', key: 'reports', label: 'Analytics', href: p('/corporate-sales/analytics'), permission: 'corp-sales:company:read' },
      { id: 'cs-reports', key: 'reports', label: 'Reports', href: p('/corporate-sales/reports'), permission: 'reports:report:read' },
      { id: 'cs-notif', key: 'notifications', label: 'Notifications', href: p('/corporate-sales/notifications'), permission: 'corp-sales:company:read' },
      { id: 'cs-mobile', key: 'crm', label: 'Mobile', href: p('/corporate-sales/mobile'), permission: 'corp-sales:company:read' },
      { id: 'cs-ai', key: 'dashboard', label: 'AI Insights', href: p('/corporate-sales/ai'), permission: 'ai:assistant:read' },
    ],
  },
  { id: 'events', key: 'concierge', label: 'Events', href: p('/events'), permission: 'events:booking:read',
    keywords: ['banquet', 'wedding', 'conference', 'event', 'hall'],
    children: [
      { id: 'ev-dash', key: 'concierge', label: 'Dashboard', href: p('/events'), permission: 'events:booking:read' },
      { id: 'ev-leads', key: 'concierge', label: 'Leads', href: p('/events/leads'), permission: 'events:lead:read' },
      { id: 'ev-clients', key: 'concierge', label: 'Clients', href: p('/events/clients'), permission: 'events:booking:read' },
      { id: 'ev-halls', key: 'rooms', label: 'Banquet Halls', href: p('/events/halls'), permission: 'events:booking:read' },
      { id: 'ev-cal', key: 'concierge', label: 'Venue Calendar', href: p('/events/calendar'), permission: 'events:booking:read' },
      { id: 'ev-book', key: 'reservations', label: 'Bookings', href: p('/events/bookings'), permission: 'events:booking:read' },
      { id: 'ev-quote', key: 'finance', label: 'Quotations', href: p('/events/quotations'), permission: 'events:booking:read' },
      { id: 'ev-pkg', key: 'concierge', label: 'Packages', href: p('/events/packages'), permission: 'events:booking:read' },
      { id: 'ev-menu', key: 'restaurant', label: 'Menu Planner', href: p('/events/menus'), permission: 'events:booking:read' },
      { id: 'ev-seat', key: 'concierge', label: 'Seating Planner', href: p('/events/seating'), permission: 'events:booking:read' },
      { id: 'ev-tasks', key: 'housekeeping', label: 'Tasks', href: p('/events/tasks'), permission: 'events:booking:read' },
      { id: 'ev-res', key: 'inventory', label: 'Resources', href: p('/events/resources'), permission: 'events:booking:read' },
      { id: 'ev-rooms', key: 'rooms', label: 'Room Blocks', href: p('/events/room-blocks'), permission: 'events:booking:read' },
      { id: 'ev-pay', key: 'finance', label: 'Payments', href: p('/events/payments'), permission: 'events:booking:read' },
      { id: 'ev-contract', key: 'documents', label: 'Contracts', href: p('/events/contracts'), permission: 'events:booking:read' },
      { id: 'ev-vendor', key: 'procurement', label: 'Vendors', href: p('/events/vendors'), permission: 'events:booking:read' },
      { id: 'ev-check', key: 'housekeeping', label: 'Checklists', href: p('/events/checklists'), permission: 'events:booking:read' },
      { id: 'ev-time', key: 'concierge', label: 'Timeline', href: p('/events/timeline'), permission: 'events:booking:read' },
      { id: 'ev-ops', key: 'housekeeping', label: 'Operations', href: p('/events/operations'), permission: 'events:booking:read' },
      { id: 'ev-owner', key: 'finance', label: 'Owner View', href: p('/events/owner'), permission: 'events:booking:read' },
      { id: 'ev-reports', key: 'reports', label: 'Reports', href: p('/events/reports'), permission: 'reports:report:read' },
      { id: 'ev-mobile', key: 'concierge', label: 'Mobile', href: p('/events/mobile'), permission: 'events:booking:read' },
      { id: 'ev-ai', key: 'dashboard', label: 'AI Insights', href: p('/events/ai'), permission: 'ai:assistant:read' },
    ],
  },
  { id: 'reports', key: 'reports', label: 'Reports', href: p('/reports'), permission: 'reports:report:read' },
  {
    id: 'analytics',
    key: 'reports',
    label: 'Analytics',
    href: p('/analytics'),
    permission: 'reports:report:read',
    keywords: ['bi', 'intelligence', 'kpi', 'revenue', 'forecast'],
    children: [
      { id: 'an-home', key: 'reports', label: 'BI Home', href: p('/analytics'), permission: 'reports:report:read' },
      { id: 'an-rev', key: 'finance', label: 'Revenue', href: p('/analytics/revenue'), permission: 'reports:report:read' },
      { id: 'an-fin', key: 'finance', label: 'Financial', href: p('/analytics/financial'), permission: 'reports:report:read' },
      { id: 'an-rooms', key: 'rooms', label: 'Rooms', href: p('/analytics/rooms'), permission: 'reports:report:read' },
      { id: 'an-book', key: 'reservations', label: 'Bookings', href: p('/analytics/booking'), permission: 'reports:report:read' },
      { id: 'an-crm', key: 'crm', label: 'CRM', href: p('/analytics/crm'), permission: 'reports:report:read' },
      { id: 'an-fnb', key: 'restaurant', label: 'Restaurant', href: p('/analytics/restaurant'), permission: 'reports:report:read' },
      { id: 'an-banq', key: 'concierge', label: 'Banquet', href: p('/analytics/banquet'), permission: 'reports:report:read' },
      { id: 'an-inv', key: 'inventory', label: 'Inventory', href: p('/analytics/inventory'), permission: 'reports:report:read' },
      { id: 'an-hr', key: 'hr', label: 'HR', href: p('/analytics/hr'), permission: 'reports:report:read' },
      { id: 'an-corp', key: 'crm', label: 'Corporate', href: p('/analytics/corporate'), permission: 'reports:report:read' },
      { id: 'an-td', key: 'concierge', label: 'Travel Desk', href: p('/analytics/travel-desk'), permission: 'reports:report:read' },
      { id: 'an-war', key: 'dashboard', label: 'War Room', href: p('/analytics/war-room'), permission: 'dashboard:overview:read' },
      { id: 'an-alert', key: 'notifications', label: 'Alerts', href: p('/analytics/alerts'), permission: 'dashboard:overview:read' },
      { id: 'an-invst', key: 'finance', label: 'Investor', href: p('/analytics/investor'), permission: 'reports:report:read' },
      { id: 'an-reports', key: 'reports', label: 'Report Builder', href: p('/analytics/reports'), permission: 'reports:report:read' },
    ],
  },
  { id: 'ai', key: 'dashboard', label: 'AI Copilot', href: p('/ai'), permission: 'ai:assistant:read', keywords: ['ai', 'copilot', 'forecast', 'predict'] },
  {
    id: 'channels',
    key: 'concierge',
    label: 'Channel Manager',
    href: p('/channels'),
    permission: 'reports:report:read',
    keywords: ['ota', 'booking.com', 'agoda', 'siteminder', 'sync', 'inventory'],
    children: [
      { id: 'ch-dash', key: 'concierge', label: 'Dashboard', href: p('/channels'), permission: 'reports:report:read' },
      { id: 'ch-conn', key: 'concierge', label: 'Connected Channels', href: p('/channels/connections'), permission: 'reports:report:read' },
      { id: 'ch-rooms', key: 'rooms', label: 'Room Mapping', href: p('/channels/room-mapping'), permission: 'rooms:room:read' },
      { id: 'ch-rates', key: 'finance', label: 'Rate Mapping', href: p('/channels/rate-mapping'), permission: 'rooms:room:read' },
      { id: 'ch-sync', key: 'concierge', label: 'Sync Logs', href: p('/channels/sync-logs'), permission: 'reports:report:read' },
      { id: 'ch-ota', key: 'reservations', label: 'OTA Bookings', href: p('/channels/ota-bookings'), permission: 'reservations:booking:read' },
    ],
  },
  {
    id: 'website',
    key: 'documents',
    label: 'Website CMS',
    href: p('/website'),
    permission: 'website:content:read',
    keywords: ['cms', 'content', 'marketing', 'seo'],
    children: [
      { id: 'cms-dash', key: 'documents', label: 'CMS Dashboard', href: p('/website'), permission: 'website:content:read' },
      { id: 'cms-homepage', key: 'documents', label: 'Homepage', href: p('/website/homepage'), permission: 'website:content:read' },
      { id: 'cms-rooms', key: 'rooms', label: 'Website Rooms', href: p('/website/rooms'), permission: 'website:content:read' },
      { id: 'cms-media', key: 'documents', label: 'Media Library', href: p('/website/media'), permission: 'website:content:read' },
      { id: 'cms-seo', key: 'documents', label: 'SEO Manager', href: p('/website/seo'), permission: 'website:content:read' },
    ],
  },
  { id: 'settings', key: 'settings', label: 'Settings', href: p('/settings'), permission: 'settings:config:read' },
  { id: 'support', key: 'notifications', label: 'Support', href: p('/support'), permission: 'settings:config:read' },
];

export function flattenNavigation(items: NavItem[] = APP_NAVIGATION): NavItem[] {
  return items.flatMap((item) => [item, ...(item.children ? flattenNavigation(item.children) : [])]);
}

export function resolveNavFromPath(pathname: string): { item?: NavItem; breadcrumbs: { label: string; href?: string }[] } {
  const flat = flattenNavigation();
  const item = flat.find((n) => n.href === pathname) ?? flat.find((n) => pathname.startsWith(`${n.href}/`));

  if (!pathname.startsWith(APP_BASE)) {
    return { breadcrumbs: [{ label: 'Home', href: p('/dashboard') }] };
  }

  const segments = pathname.replace(APP_BASE, '').split('/').filter(Boolean);
  const breadcrumbs = [{ label: 'Home', href: p('/dashboard') }];

  let path = APP_BASE;
  for (const seg of segments) {
    path += `/${seg}`;
    const match = flat.find((n) => n.href === path);
    breadcrumbs.push({
      label: match?.label ?? seg.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      href: path,
    });
  }

  return { item, breadcrumbs };
}

export const QUICK_ACTIONS = [
  { id: 'front-desk', label: 'Front Desk', href: p('/front-desk'), keywords: ['reception', 'operations'] },
  { id: 'new-reservation', label: 'New Reservation', href: p('/reservations/new'), keywords: ['booking'] },
  { id: 'walk-in', label: 'Walk-in Guest', href: p('/front-desk/walk-in'), keywords: ['guest'] },
  { id: 'check-in', label: 'Room Check-in', href: p('/front-desk/check-in'), keywords: ['arrival'] },
  { id: 'check-out', label: 'Room Checkout', href: p('/front-desk/check-out'), keywords: ['departure'] },
  { id: 'arrivals', label: 'Arrival Board', href: p('/front-desk/arrivals'), keywords: ['arrival'] },
  { id: 'departures', label: 'Departure Board', href: p('/front-desk/departures'), keywords: ['departure'] },
  { id: 'restaurant-bill', label: 'Restaurant Billing', href: p('/restaurant/billing'), keywords: ['pos'] },
  { id: 'invoice', label: 'Create Invoice', href: p('/finance/invoices/new'), keywords: ['finance'] },
  { id: 'add-guest', label: 'Add Guest', href: p('/crm/guests'), keywords: ['crm'] },
  { id: 'report', label: 'Generate Report', href: p('/reports'), keywords: ['analytics'] },
] as const;

export function isAppRoute(pathname: string): boolean {
  return pathname === APP_BASE || pathname.startsWith(`${APP_BASE}/`);
}
